language: c
compiler:
- clang
- gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

before_install:
- sudo add-apt-repository ppa:dns/gnu -y
- sudo apt-get -qq update
install:
- sudo apt-get install --only-upgrade autoconf
- sudo apt-get install automake libtool pkg-config check
- sudo apt-get install libmicrohttpd-dev libossp-uuid-dev curl
- ./autogen.sh

